# Coleta de Dados no MySQL utilizando o R

In [1]:
#Instalação do pacote
install.packages('RMariaDB')

package 'RMariaDB' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\luciano\AppData\Local\Temp\RtmpO0RhQu\downloaded_packages

In [2]:
#importação do pacote

#Importar pacote RMariaDB se ele ainda não foi carregado
if (!"RMariaDB" %in% (.packages())){require(RMariaDB)}

Loading required package: RMariaDB
Warning message:
"package 'RMariaDB' was built under R version 3.6.3"

In [3]:
#Conectar ao SGDB MySQL --> Banco de Dados bootcamp
con <- dbConnect(MariaDB(), user = "root", password = "root",
                dbname = "bootcamp", host = "localhost", serverTimezone = 'UTC')

In [4]:
#Para listar quais tabelas existem no esquema .bootcamp execute:

#Ler a lista de tabelas no DB
tables <- dbListTables(con)
tables

[1] "caracteristicaimovel"  "caracteristicasgerais" "cidade"
[4] "estado"                "imovel"                "tipounidade"

In [5]:
#Para consultar os dados de uma tabela, execute:
#dbReadTable(nome-da-conexao, "nome-da-tabela")

#Consultar os dados da tabela *estado*
tabledata <- dbReadTable(con, "estado")
tabledata

   CodEstadoIBGE NomeEstado          SiglaEstado Regiao
1  11            Rondonia            RO          Norte
2  12            Acre                AC          Norte
3  13            Amazonas            AM          Norte
4  14            Roraima             RO          Norte
5  15            Para                PA          Norte
6  16            Amapa               AP          Norte
7  17            Tocantins           TO          Norte
8  21            Maranhao            MA          Nordeste
9  22            Piaui               PI          Nordeste
10 23            Ceara               CE          Nordeste
11 24            Rio Grande do Norte RN          Nordeste
12 25            Paraíba             PB          Nordeste
13 26            Pernambuco          PE          Nordeste
14 27            Alagoas             AL          Nordeste
15 28            Sergipe             SE          Nordeste
16 29            Bahia               BA          Nordeste
17 31            Minas Gerais        MG          Sudeste
18 32            Espírito Santo      MG          Sudeste
19 33            Rio de Janeiro      RJ          Sudeste
20 35            São Paulo           SP          Sudeste
21 41            Parana              PR          Sudeste
22 42            Santa Catarina      SC          Sul
23 43            Rio Grande do Sul   RS          Sul
24 50            Mato Grosso do Sul  MS          Centro-Oeste
25 51            Mato Grosso         MT          Centro-Oeste
26 52            Goiás               GO          Centro-Oeste
27 53            Distrito Federal    DF          Centro-Oeste

In [6]:
#Consultar os dados da tabela *cidade*
tabledata <- dbReadTable(con, "cidade")
tabledata

     CodigoCompletoIBGE CodigoCidadeIBGE NomeCidade
1    1100015            15               Alta Floresta D Oeste
2    1100023            23               Ariquemes
3    1100031            31               Cabixi
4    1100049            49               Cacoal
5    1100056            56               Cerejeiras
6    1100064            64               Colorado do Oeste
7    1100072            72               Corumbiara
8    1100080            80               Costa Marques
9    1100098            98               Espigão D Oeste
10   1100106            106              Guajará-Mirim
11   1100114            114              Jaru
12   1100122            122              Ji-Paraná
13   1100130            130              Machadinho D Oeste
14   1100148            148              Nova Brasilândia D Oeste
15   1100155            155              Ouro Preto do Oeste
16   1100189            189              Pimenta Bueno
17   1100205            205              Porto Velho
18   1100254            254              Presidente Médici
19   1100262            262              Rio Crespo
20   1100288            288              Rolim de Moura
21   1100296            296              Santa Luzia D Oeste
22   1100304            304              Vilhena
23   1100320            320              São Miguel do Guaporé
24   1100338            338              Nova Mamoré
25   1100346            346              Alvorada D Oeste
26   1100379            379              Alto Alegre dos Parecis
27   1100403            403              Alto Paraíso
28   1100452            452              Buritis
29   1100502            502              Novo Horizonte do Oeste
30   1100601            601              Cacaulândia
...  ...                ...              ...
5541 5220108            20108            São Luís de Montes Belos
5542 5220157            20157            São Luiz do Norte
5543 5220207            20207            São Miguel do Araguaia
5544 5220264            20264            São Miguel do Passa Quatro
5545 5220280            20280            São Patrício
5546 5220405            20405            São Simão
5547 5220454            20454            Senador Canedo
5548 5220504            20504            Serranópolis
5549 5220603            20603            Silvânia
5550 5220686            20686            Simolândia
5551 5220702            20702            Sítio D Abadia
5552 5221007            21007            Taquaral de Goiás
5553 5221080            21080            Teresina de Goiás
5554 5221197            21197            Terezópolis de Goiás
5555 5221304            21304            Três Ranchos
5556 5221403            21403            Trindade
5557 5221452            21452            Trombas
5558 5221502            21502            Turvânia
5559 5221551            21551            Turvelândia
5560 5221577            21577            Uirapuru
5561 5221601            21601            Uruaçu
5562 5221700            21700            Uruana
5563 5221809            21809            Urutaí
5564 5221858            21858            Valparaíso de Goiás
5565 5221908            21908            Varjão
5566 5222005            22005            Vianópolis
5567 5222054            22054            Vicentinópolis
5568 5222203            22203            Vila Boa
5569 5222302            22302            Vila Propício
5570 5300108            108              Brasília
     CodEstadoIBGE
1    11
2    11
3    11
4    11
5    11
6    11
7    11
8    11
9    11
10   11
11   11
12   11
13   11
14   11
15   11
16   11
17   11
18   11
19   11
20   11
21   11
22   11
23   11
24   11
25   11
26   11
27   11
28   11
29   11
30   11
...  ...
5541 52
5542 52
5543 52
5544 52
5545 52
5546 52
5547 52
5548 52
5549 52
5550 52
5551 52
5552 52
5553 52
5554 52
5555 52
5556 52
5557 52
5558 52
5559 52
5560 52
5561 52
5562 52
5563 52
5564 52
5565 52
5566 52
5567 52
5568 52
5569 52
5570 53

In [7]:
#Consultar os dados da tabela *imovel*
tabledata <- dbReadTable(con, "imovel")
tabledata

   idImovel codRegistro   Disponibilidade idTipoUnidade areaImovel valorIPTU
1   1       7658769889078 V               4              56        2110
2   2       32435464357   A               1             165        3785
3   3       2724547425427 A               6              99        3565
4   4       25775751253   V               4              73        3705
5   5       257247247     V               5             185        3132
6   6       34523436426   A               5              66        2209
7   7       3508610000000 V               6             148        3506
8   8       9342440000000 V               4              84        2796
9   9       4565600000000 A               5             144        3320
10 10       2149040000000 A               1             110        1777
11 11       943254000000  A               3             191        2977
12 12       878641000000  V               2             138        3132
13 13       6658780000000 A               6              67        2624
14 14       3850750000000 V               5              57        2597
15 15       46854751611   A               4             149        1916
16 16       6580820000000 V               6             118        1653
17 17       4354230000000 V               4              55        4066
18 18       2712570000000 A               6             140        2964
19 19       2995820000000 A               3              57        3643
20 20       1785130000000 A               1             121        1788
21 21       1584630000000 A               3             178        2294
22 22       8306000000000 A               5             149        2932
23 23       2308470000000 A               4              82        1837
24 24       8894910000000 A               4              94        3621
25 25       5010480000000 A               1              73        3063
26 26       7623850000000 A               3             141        4047
27 27       8004320000000 A               4             110        1884
28 28       2530160000000 V               5              43        3217
29 29       6346820000000 V               3             181        3667
30 30       396987000000  A               2             191        1791
31 31       406987000000  A               1              97        1550
32 32       311987000000  V               2              83        1791
33 33       314587000000  A               3              91        1890
34 34       396988000000  V               1             251        2090
35 35       985647000000  A               4              85        2350
   valorCondominio qtdeQuartos qtdeBanheiro qtdeSuite qtdeSala qtdeVagas
1   493            1           1            1         1        3
2     0            3           2            0         2        2
3  1040            4           2            1         1        0
4   538            1           2            0         1        3
5  1072            1           2            0         2        3
6  1120            4           1            2         1        1
7   178            4           1            2         2        1
8   812            2           1            0         2        3
9   773            1           3            2         2        1
10    0            4           2            2         1        0
11 1101            3           2            0         2        2
12    0            4           1            2         2        3
13  189            3           3            2         2        3
14  560            3           1            2         1        3
15  229            3           1            2         2        0
16  613            2           1            0         2        0
17  463            3           1            2         2        2
18  967            3           3            2         1        2
19  361            2           2            0         1        1
20    0            3           1            1         1        0
21 1006            3           1            0         2        3
22  207            1           2            2         1        0
23  432            1           2            0         2        0
24  150            1           3            0         2        1
25    0            3           3            0         2        2
26  883            2           2            2         2        0
27 1187            4           1            2         2        2
28  516            3           2            2         2        3
29 1002            2           3            0         1        0
30    0            4           3            0         1        3
31    0            2           2            1         1        2
32  100            2           2            1         2        0
33  300            3           3            2         1        2
34    0            4           3            2         2        3
35  650            2           2            0         1        1
   CodigoCompletoIBGE
1  4204178
2  1501105
3  5107305
4  2917334
5  3542909
6  4305355
7  2901205
8  4321501
9  2604700
10 5103700
11 3140308
12 2606002
13 3502200
14 4109302
15 3138906
16 2807204
17 4320321
18 3127602
19 3518701
20 2705002
21 3171402
22 2100501
23 4306106
24 2112605
25 5216452
26 4114609
27 4309258
28 4313011
29 4313607
30 3108701
31 3203205
32 1101435
33 1200104
34 3136702
35 4321501

In [10]:
#Consultar os dados da tabela *tipounidade*
tabledata <- dbReadTable(con, "tipounidade")
tabledata

  idTipoUnidade dscTipoUnidade
1 1             Casa
2 2             Casa geminada
3 3             Apartamento tipo
4 4             Apartamento cobertura
5 5             Apartamento área privativa
6 6             Flat
7 7             Loft

In [9]:
#Para executar um comando SQL execute:
#dbSendQuery(nome-da-conexão, "comando")

#Vamos inserir uma nova linha na tabela tipounidade
#Criar o comando e salvar na variável query
query <- "INSERT INTO tipounidade(idTipoUnidade, dscTipoUnidade) VALUES (7, 'Loft');"

#Opcional
print(query)

results <- dbSendQuery(con, query)
results

#Limpar resultados
dbClearResult(results)

[1] "INSERT INTO tipounidade(idTipoUnidade, dscTipoUnidade) VALUES (7, 'Loft');"

<MariaDBResult>
  SQL  INSERT INTO tipounidade(idTipoUnidade, dscTipoUnidade) VALUES (7, 'Loft');
  ROWS Fetched: 0 [complete]
       Changed: 1

In [11]:
#Consultar os dados da tabela *tipounidade*
tabledata <- dbReadTable(con, "tipounidade")
tabledata

  idTipoUnidade dscTipoUnidade
1 1             Casa
2 2             Casa geminada
3 3             Apartamento tipo
4 4             Apartamento cobertura
5 5             Apartamento área privativa
6 6             Flat
7 7             Loft

In [12]:
#Inserção por parâmetros
id <- 8
desc <- 'Chácara'

query <- paste("INSERT INTO tipounidade(idTipoUnidade, dscTipoUnidade) VALUES (",id,",'",desc,"');", sep = '')

#Opcional
print(query)

results <- dbSendQuery(con, query)
results

#Limpar resultados
dbClearResult(results)

[1] "INSERT INTO tipounidade(idTipoUnidade, dscTipoUnidade) VALUES (8,'Chácara');"

<MariaDBResult>
  SQL  INSERT INTO tipounidade(idTipoUnidade, dscTipoUnidade) VALUES (8,'Chácara');
  ROWS Fetched: 0 [complete]
       Changed: 1

In [13]:
#Consultar os dados da tabela *tipounidade*
tabledata <- dbReadTable(con, "tipounidade")
tabledata

  idTipoUnidade dscTipoUnidade
1 1             Casa
2 2             Casa geminada
3 3             Apartamento tipo
4 4             Apartamento cobertura
5 5             Apartamento área privativa
6 6             Flat
7 7             Loft
8 8             Chácara

In [14]:
#Instalação de pacote
install.packages('xlsx')

also installing the dependencies 'rJava', 'xlsxjars'

package 'rJava' successfully unpacked and MD5 sums checked
package 'xlsxjars' successfully unpacked and MD5 sums checked
package 'xlsx' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\luciano\AppData\Local\Temp\RtmpO0RhQu\downloaded_packages

In [15]:
#importação do pacote

#Importar pacote xlsx se ele ainda não foi carregado
if (!"xlsx" %in% (.packages())){require(xlsx)}

datasetpath <- 'C:/Users/luciano/IGTI/dados'

filename <- paste(datasetpath, "/estados.xlsx", sep = '')
filename

insertdata <- read.xlsx(filename, sheetIndex = 1, header = TRUE, encoding = "UTF-8")
insertdata

Loading required package: xlsx
Warning message:
"package 'xlsx' was built under R version 3.6.3"

[1] "C:/Users/luciano/IGTI/dados/estados.xlsx"

   CodEstadoIBGE nomeestado          siglaestado regiao
1  11            Rondónia            RO          Norte
2  12            Acre                AC          Norte
3  13            Amazonas            AM          Norte
4  14            Roraima             R           Norte
5  15            Pará                PA          Norte
6  16            Amapá               AP          Norte
7  17            Tocantins           TO          Norte
8  21            Maranhão            MA          Nordeste
9  22            Piauí               PI          Nordeste
10 23            Ceará               CE          Nordeste
11 24            Rio Grande do Norte RN          Nordeste
12 25            Paraíba             PB          Nordeste
13 26            Pernambuco          PE          Nordeste
14 27            Alagoas             AL          Nordeste
15 28            Sergipe             SE          Nordeste
16 29            Bahia               BA          Nordeste
17 31            Minas Gerais        MG          Sudeste
18 32            Espírito Santo      ES          Sudeste
19 33            Rio de Janeiro      RJ          Sudeste
20 35            São Paulo           SP          Sudeste
21 41            Paraná              PR          Sul
22 42            Santa Catarina      SC          Sul
23 43            Rio Grande do Sul   RS          Sul
24 50            Mato Grosso do Sul  MS          Centro-Oeste
25 51            Mato Grosso         MT          Centro-Oeste
26 52            Goiás               GO          Centro-Oeste
27 53            Distrito Federal    DF          Centro-Oeste

In [ ]:
dbWriteTable(con, 'estado', insertdata, append = TRUE)

In [16]:
#Consultar os dados da tabela *estado*
tabledata <- dbReadTable(con, "estado")
tabledata

   CodEstadoIBGE NomeEstado          SiglaEstado Regiao
1  11            Rondonia            RO          Norte
2  12            Acre                AC          Norte
3  13            Amazonas            AM          Norte
4  14            Roraima             RO          Norte
5  15            Para                PA          Norte
6  16            Amapa               AP          Norte
7  17            Tocantins           TO          Norte
8  21            Maranhao            MA          Nordeste
9  22            Piaui               PI          Nordeste
10 23            Ceara               CE          Nordeste
11 24            Rio Grande do Norte RN          Nordeste
12 25            Paraíba             PB          Nordeste
13 26            Pernambuco          PE          Nordeste
14 27            Alagoas             AL          Nordeste
15 28            Sergipe             SE          Nordeste
16 29            Bahia               BA          Nordeste
17 31            Minas Gerais        MG          Sudeste
18 32            Espírito Santo      MG          Sudeste
19 33            Rio de Janeiro      RJ          Sudeste
20 35            São Paulo           SP          Sudeste
21 41            Parana              PR          Sudeste
22 42            Santa Catarina      SC          Sul
23 43            Rio Grande do Sul   RS          Sul
24 50            Mato Grosso do Sul  MS          Centro-Oeste
25 51            Mato Grosso         MT          Centro-Oeste
26 52            Goiás               GO          Centro-Oeste
27 53            Distrito Federal    DF          Centro-Oeste

In [17]:
#Importar pacote xlsx se ele ainda não foi carregado
if (!"xlsx" %in% (.packages())){require(xlsx)}

query <- "SELECT * FROM estado;"

results <- dbGetQuery(con, query)
results

   CodEstadoIBGE NomeEstado          SiglaEstado Regiao
1  11            Rondonia            RO          Norte
2  12            Acre                AC          Norte
3  13            Amazonas            AM          Norte
4  14            Roraima             RO          Norte
5  15            Para                PA          Norte
6  16            Amapa               AP          Norte
7  17            Tocantins           TO          Norte
8  21            Maranhao            MA          Nordeste
9  22            Piaui               PI          Nordeste
10 23            Ceara               CE          Nordeste
11 24            Rio Grande do Norte RN          Nordeste
12 25            Paraíba             PB          Nordeste
13 26            Pernambuco          PE          Nordeste
14 27            Alagoas             AL          Nordeste
15 28            Sergipe             SE          Nordeste
16 29            Bahia               BA          Nordeste
17 31            Minas Gerais        MG          Sudeste
18 32            Espírito Santo      MG          Sudeste
19 33            Rio de Janeiro      RJ          Sudeste
20 35            São Paulo           SP          Sudeste
21 41            Parana              PR          Sudeste
22 42            Santa Catarina      SC          Sul
23 43            Rio Grande do Sul   RS          Sul
24 50            Mato Grosso do Sul  MS          Centro-Oeste
25 51            Mato Grosso         MT          Centro-Oeste
26 52            Goiás               GO          Centro-Oeste
27 53            Distrito Federal    DF          Centro-Oeste

In [19]:
#Salva o resultado da query no arquivo CSV
write.csv(results, "C:/Users/luciano/IGTI/dados/estadosDB.csv", row.names = FALSE, quote = FALSE)

#dbCommit(con)

In [ ]:
#Criar uma tabela vazia
query <- "CREATE TABLE caracteristicasgerais(
                idcaracteristicasGerais int NOT NULL AUTO_INCREMENT,
                dsccaracteristicasGerais varchar(150) NOT NULL,
                PRIMARY KEY (idcaracteristicasGerais));"

results <- dbSendQuery(con, query)
results

In [20]:
tables <- dbListTables(con)
tables

[1] "caracteristicaimovel"  "caracteristicasgerais" "cidade"
[4] "estado"                "imovel"                "tipounidade"

In [21]:
#Desconectar o Banco de Dados
dbDisconnect(con)